trigger:
  - master
pr:
  - master

resources:
  repositories:
    - repository: templates
      type: github
      name: Vermont-Labor-UI/pipeline-templates
      endpoint: Vermont-iUS

variables:
  majorVersion: 1

jobs:
  - template: helm/standalone-helm-chart-pipeline.yaml@templates
    parameters:
      project: 'common-template'
      helmChartLocation: '.'
      helmChartName: 'common'
      stateCode: 0
      majorVersion:  $(majorVersion)
