---
replicaCount: 2

image:
  repository: vtiusdev.azurecr.io/ius.employerwages.service
  tag: 0.2.9.2502

nameOverride: ""
fullnameOverride: ""

ingressSettings:
  nginx.ingress.kubernetes.io/client-max-body-size: 10m

nodeSelector: {}

tolerations: []

affinity: {}

global:
  DisableDataProtectionSecret: true
  replicaCount: 3
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 25m
      memory: 16m
  ClientStateName: "State"
  Environment: "Envrionment"
  ingress:
    host: k8-ius.com
    tlssecret: development-id-gov-tlssecret
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
  HelmNames:
    InternalWeb:
      TestChartService: testchart-service
additionalVolumes:
  - name: aspose
    mountPath: /lib/sure
    type: "configMap"
    configMapName: "my-special-config-map-{{.Release.Name}}"
additional_env_vars:
  betterStateName: cmon-just-work
  Debug_level: "super duper uper vuper verbos"
  APPSETTINGS_LOCATION: "hmmmm what happens now"
